language: ruby
rvm:
  - 2.4.1
script: bundle exec jekyll build
branches:
  only:
    - deploy
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false